import { SolrResponseHeader } from '../types';

type NodePropertiesNames =
  | 'java.vendor'
  | 'sun.java.launcher'
  | 'sun.management.compiler'
  | 'os.name'
  | 'solr.jetty.inetaccess.includes'
  | 'java.vm.specification.vendor'
  | 'java.runtime.version'
  | 'solr.jetty.host'
  | 'STOP.KEY'
  | 'user.name'
  | 'solr.solr.home'
  | 'user.language'
  | 'sun.boot.library.path'
  | 'java.vm.compressedOopsMode'
  | 'java.version'
  | 'user.timezone'
  | 'jetty.base'
  | 'sun.arch.data.model'
  | 'jetty.port'
  | 'sun.jnu.encoding'
  | 'file.separator'
  | 'java.specification.name'
  | 'java.class.version'
  | 'java.security.properties'
  | 'jetty.git.hash'
  | 'user.country'
  | 'java.home'
  | 'java.vm.info'
  | 'solr.internal.network.permission'
  | 'os.version'
  | 'solr.log.dir'
  | 'solr.jetty.inetaccess.excludes'
  | 'path.separator'
  | 'java.vm.version'
  | 'jetty.tag.version'
  | 'java.security.policy'
  | 'jdk.tls.rejectClientInitiatedRenegotiation'
  | 'sun.io.unicode.encoding'
  | 'user.home'
  | 'java.version.date'
  | 'jetty.build'
  | 'java.specification.vendor'
  | 'java.library.path'
  | 'java.vendor.url'
  | 'solr.data.home'
  | 'java.vm.vendor'
  | 'STOP.PORT'
  | 'zookeeper.4lw.commands.whitelist'
  | 'disableAdminUI'
  | 'java.runtime.name'
  | 'sun.java.command'
  | 'java.class.path'
  | 'zkRun'
  | 'jetty.version'
  | 'native.encoding'
  | 'jdk.debug'
  | 'java.vm.specification.name'
  | 'zookeeper.admin.enableServer'
  | 'java.vm.specification.version'
  | 'sun.cpu.endian'
  | 'java.io.tmpdir'
  | 'java.vendor.url.bug'
  | 'zookeeper.jmx.log4j.disable'
  | 'os.arch'
  | 'user.dir'
  | 'java.security.manager'
  | 'line.separator'
  | 'solr.default.confdir'
  | 'solr.install.dir'
  | 'solr.log.requestlog.enabled'
  | 'java.vm.name'
  | 'zkClientTimeout'
  | 'log4j.configurationFile'
  | 'file.encoding'
  | 'java.specification.version'
  | 'java.vendor.version'
  | 'jetty.home'
  | string;

/**
 * @version Solr 8.x, 9.x
 */
export interface SolrCollectionNodePropertiesGetResponse {
  responseHeader: SolrResponseHeader;
  'system.properties': {
    [k: NodePropertiesNames]: string;
  };
}
